version: '3.5'

networks:
  iroha-network:
    name: iroha-network
    attachable: true
    ipam:
      config:
        - subnet: 12.163.181.0/24

volumes:
  iroha-postgres-vol1:
   name: iroha-postgres-vol1
  blockstore1:
   name: blockstore1

services:
  some-postgres1:
    image: postgres:13
    container_name: some-postgres1
    command: -c max_prepared_transactions=100
    restart: unless-stopped  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      iroha-network:
        ipv4_address: 128.163.181.53
    volumes:
      - type: volume
        source: iroha-postgres-vol1
        target: /var/lib/postgresql/data

  iroha1:
    image: hyperledger/iroha:latest
    container_name: iroha1
    restart: unless-stopped  
    depends_on:
      - some-postgres1
    tty: true
    environment:
      - KEY=node1
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    networks:
      iroha-network:
        ipv4_address: 128.163.181.53
    volumes:
      - ./node1:/opt/iroha_data
      - type: volume
        source: blockstore1
        target: /tmp/block_store1
